// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartMeal.Data.Data;

namespace SmartMeal.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190503145932_Facebook")]
    partial class Facebook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618



            modelBuilder
               .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
               .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
               .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SmartMeal.Models.Models.User", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Email")
                    .IsRequired();

                b.Property<long>("FacebookId");

                b.Property<string>("Password");

                b.HasKey("Id");

                b.ToTable("User");
            });
#pragma warning restore 612, 618
        }
    }
}
