version: '3.4'

networks:
  api-dev:
    driver: bridge 

services:
  db:
    image: postgres:10.4
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    networks:
      - api-dev

  pgadmin:
    image: dpage/pgadmin4:2.1
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    env_file:
      - .env
    networks:
      - api-dev
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin_data: